version: '3.8'

services:
  localstack:
    container_name: localstack
    image: localstack/localstack:2.3
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,dynamodb,lambda,sqs
      - DEBUG=1
      - AWS_DEFAULT_REGION=us-east-1
      - LOCALSTACK_ACKNOWLEDGE_ACCOUNT_REQUIREMENT=1
    volumes:
      - "./localstack/init:/etc/localstack/init/ready.d"
      - "./services:/var/task/services"
      - "/var/run/docker.sock:/var/run/docker.sock"