version: '3.8'

services:
  localstack:
    container_name: localstack
    image: localstack/localstack:3.4.0
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,dynamodb,lambda,sqs,logs
      - AWS_DEFAULT_REGION=us-east-1
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "./localstack/init:/etc/localstack/init/ready.d"
      - "./services:/var/task/services"
      - "/var/run/docker.sock:/var/run/docker.sock"